import js from "@eslint/js";
import pluginQuery from "@tanstack/eslint-plugin-query";
import pluginRouter from "@tanstack/eslint-plugin-router";
import boundaries from "eslint-plugin-boundaries";
import prettier from "eslint-config-prettier/flat";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Architecture elements (see "Architecture rules" in CLAUDE.md).
 * Each folder below is one element; `feature` captures the feature name so
 * cross-feature imports can be limited to the other feature's index.ts.
 */
const elements = [
  { type: "app", pattern: "src/app" },
  { type: "routes", pattern: "src/routes" },
  { type: "feature", pattern: "src/features/*", capture: ["featureName"] },
  { type: "ui", pattern: "src/components/ui" },
  { type: "common", pattern: "src/components/common" },
  { type: "api", pattern: "src/api" },
  { type: "domain", pattern: "src/domain" },
  { type: "lib", pattern: "src/lib" },
  { type: "test", pattern: "src/test" },
  { type: "contracts", pattern: "shared/contracts" },
  { type: "mock-server", pattern: "mock-server" },
];

/** Allowed dependencies per element type; anything not listed is an error. */
const allowedDependencies = {
  app: ["routes", "api", "ui", "common", "lib"],
  routes: ["app", "feature", "ui", "common", "api", "domain", "lib"],
  feature: ["ui", "common", "api", "domain", "lib", "contracts"],
  common: ["ui", "domain", "lib"],
  ui: ["lib"],
  api: ["contracts", "lib"],
  domain: ["contracts"],
  lib: [],
  test: [
    "app",
    "routes",
    "feature",
    "ui",
    "common",
    "api",
    "domain",
    "lib",
    "contracts",
  ],
  contracts: [],
  "mock-server": ["contracts"],
};

const boundaryPolicies = [
  ...Object.entries(allowedDependencies).map(([from, to]) => ({
    from: { element: { type: from } },
    allow: { to: { element: { types: { anyOf: [from, ...to] } } } },
  })),
  // Features import other features only through their public index.ts
  {
    from: { element: { type: "feature" } },
    disallow: {
      to: {
        element: {
          type: "feature",
          captured: { featureName: "!{{ from.element.captured.featureName }}" },
        },
      },
    },
  },
  {
    from: { element: { type: "feature" } },
    allow: {
      to: { element: { type: "feature", fileInternalPath: "index.ts" } },
    },
  },
  // Test files may use the shared test helpers in src/test
  {
    from: { file: { categories: "test" } },
    allow: { to: { element: { type: "test" } } },
  },
];

export default defineConfig([
  globalIgnores([
    "dist",
    "coverage",
    "playwright-report",
    "test-results",
    // Generated by the TanStack Router plugin
    "src/routeTree.gen.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, tseslint.configs.strictTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    extends: [
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      pluginQuery.configs["flat/recommended"],
      pluginRouter.configs["flat/recommended"],
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Route files export `Route` alongside their components
    files: ["src/routes/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": [
        "error",
        { allowExportNames: ["Route"] },
      ],
    },
  },
  {
    files: ["src/**/*.{ts,tsx}", "shared/**/*.ts", "mock-server/**/*.ts"],
    plugins: { boundaries },
    settings: {
      "boundaries/elements": elements,
      "boundaries/files": [{ pattern: "**/*.test.{ts,tsx}", category: "test" }],
      "import/resolver": { typescript: { alwaysTryTypes: true } },
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        { default: "disallow", policies: boundaryPolicies },
      ],
    },
  },
  {
    files: ["**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: { globals: globals.node },
  },
  prettier,
]);
